-- Seed: portfolio earnings import (surveys + cashback)
-- Run this in Supabase SQL Editor AFTER portfolio_earnings.sql

insert into public.portfolio_earnings (id, title, provider, kind, date, amount_eur, created_at, updated_at) values

  -- March 2026
  (gen_random_uuid()::text, 'WhatYouExpect',           'Vale',       'survey',   '2026-03-13',  5.00, now(), now()),
  (gen_random_uuid()::text, 'Amazon',                  'LetyShops',  'cashback', '2026-03-11',  6.20, now(), now()),
  (gen_random_uuid()::text, 'Amazon',                  'Bleap',      'cashback', '2026-03-10',  1.24, now(), now()),
  (gen_random_uuid()::text, 'beRuby',                  'PayPal',     'survey',   '2026-03-09', 10.00, now(), now()),
  (gen_random_uuid()::text, 'Unibanco',                'Unibanco',   'cashback', '2026-03-07', 20.00, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Curve',      'cashback', '2026-03-07',  0.25, now(), now()),
  (gen_random_uuid()::text, 'Bagga',                   'Curve',      'cashback', '2026-03-07',  0.05, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Curve',      'cashback', '2026-03-06',  1.59, now(), now()),
  (gen_random_uuid()::text, 'WhatYouExpect',           'Vale',       'survey',   '2026-03-05',  5.00, now(), now()),
  (gen_random_uuid()::text, 'MEO',                     'Curve',      'cashback', '2026-03-04',  2.49, now(), now()),
  (gen_random_uuid()::text, 'Amazon',                  'LetyShops',  'cashback', '2026-03-03',  0.26, now(), now()),

  -- February 2026
  (gen_random_uuid()::text, 'EarnStar',                'PayPal',     'survey',   '2026-02-28',  1.64, now(), now()),
  (gen_random_uuid()::text, 'PrimeOpinion',            'Revolut',    'survey',   '2026-02-28',  3.00, now(), now()),
  (gen_random_uuid()::text, 'AttaPoll',                'PayPal',     'survey',   '2026-02-28',  9.05, now(), now()),
  (gen_random_uuid()::text, 'Amazon',                  'LetyShops',  'cashback', '2026-02-28',  0.02, now(), now()),
  (gen_random_uuid()::text, 'Amazon',                  'LetyShops',  'cashback', '2026-02-28',  2.69, now(), now()),
  (gen_random_uuid()::text, 'MEO',                     'Curve',      'cashback', '2026-02-25',  0.42, now(), now()),
  (gen_random_uuid()::text, 'Frango e Vicios',         'Cetelem',    'cashback', '2026-02-21',  0.58, now(), now()),
  (gen_random_uuid()::text, 'LIDL',                    'Cetelem',    'cashback', '2026-02-21',  0.27, now(), now()),
  (gen_random_uuid()::text, 'LIDL',                    'Curve',      'cashback', '2026-02-20',  0.09, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Curve',      'cashback', '2026-02-20',  1.03, now(), now()),
  (gen_random_uuid()::text, 'A Batina',                'Cetelem',    'cashback', '2026-02-19',  0.75, now(), now()),
  (gen_random_uuid()::text, 'Ivo Macedo Lisboa Luz',   'Cetelem',    'cashback', '2026-02-18',  0.42, now(), now()),
  (gen_random_uuid()::text, 'Amazon',                  'LetyShops',  'cashback', '2026-02-15',  6.95, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Curve',      'cashback', '2026-02-14',  0.39, now(), now()),
  (gen_random_uuid()::text, 'Mercadona',               'Cetelem',    'cashback', '2026-02-14',  1.15, now(), now()),
  (gen_random_uuid()::text, 'Frangos e Vicios',        'Cetelem',    'cashback', '2026-02-14',  0.58, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Cetelem',    'cashback', '2026-02-13',  1.27, now(), now()),
  (gen_random_uuid()::text, 'Prozis',                  'Cetelem',    'cashback', '2026-02-13',  2.02, now(), now()),
  (gen_random_uuid()::text, 'Vitaminas',               'Cetelem',    'cashback', '2026-02-13',  0.11, now(), now()),
  (gen_random_uuid()::text, 'Companhia das Sandes',    'Cetelem',    'cashback', '2026-02-13',  0.20, now(), now()),
  (gen_random_uuid()::text, 'LaoLao',                  'Cetelem',    'cashback', '2026-02-13',  0.15, now(), now()),
  (gen_random_uuid()::text, 'Vitaminas',               'Cetelem',    'cashback', '2026-02-13',  0.31, now(), now()),
  (gen_random_uuid()::text, 'Sabores e Mondego',       'Cetelem',    'cashback', '2026-02-13',  0.30, now(), now()),
  (gen_random_uuid()::text, 'LaoLao',                  'Cetelem',    'cashback', '2026-02-13',  0.15, now(), now()),
  (gen_random_uuid()::text, 'Legumes e Outros Vicios', 'Cetelem',    'cashback', '2026-02-13',  1.10, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Cetelem',    'cashback', '2026-02-13',  0.73, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Cetelem',    'cashback', '2026-02-13',  0.29, now(), now()),
  (gen_random_uuid()::text, 'Pingo Doce',              'Cetelem',    'cashback', '2026-02-13',  0.17, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Cetelem',    'cashback', '2026-02-13',  0.72, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Cetelem',    'cashback', '2026-02-13',  0.61, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Cetelem',    'cashback', '2026-02-13',  0.09, now(), now()),
  (gen_random_uuid()::text, 'Unibanco',                'Unibanco',   'cashback', '2026-02-08', 20.00, now(), now()),
  (gen_random_uuid()::text, 'Bybit',                   'ByBit',      'cashback', '2026-02-04', 25.00, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Curve',      'cashback', '2026-02-01',  0.11, now(), now()),

  -- January 2026
  (gen_random_uuid()::text, 'Top Surveys',             'PayPal',     'survey',   '2026-01-31',  1.00, now(), now()),
  (gen_random_uuid()::text, 'PrimeOpinion',            'Revolut',    'survey',   '2026-01-31',  3.00, now(), now()),
  (gen_random_uuid()::text, 'MultiPolls',              'PayPal',     'survey',   '2026-01-31',  7.00, now(), now()),
  (gen_random_uuid()::text, 'EarnStar',                'PayPal',     'survey',   '2026-01-31',  4.00, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Curve',      'cashback', '2026-01-30',  0.25, now(), now()),
  (gen_random_uuid()::text, 'Bybit',                   'ByBit',      'cashback', '2026-01-26', 25.00, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Curve',      'cashback', '2026-01-23',  0.71, now(), now()),
  (gen_random_uuid()::text, 'Booking',                 'Curve',      'cashback', '2026-01-19',  0.59, now(), now()),
  (gen_random_uuid()::text, 'Booking',                 'Curve',      'cashback', '2026-01-19',  3.54, now(), now()),
  (gen_random_uuid()::text, 'Bybit',                   'ByBit',      'cashback', '2026-01-19', 25.00, now(), now()),
  (gen_random_uuid()::text, 'Leroy Merlin',            'Curve',      'cashback', '2026-01-18',  0.06, now(), now()),
  (gen_random_uuid()::text, 'Questionários Online',    'Vale',       'survey',   '2026-01-16', 10.00, now(), now()),
  (gen_random_uuid()::text, 'IKEA',                    'Curve',      'cashback', '2026-01-15',  0.33, now(), now()),
  (gen_random_uuid()::text, 'Leroy Merlin',            'Curve',      'cashback', '2026-01-11',  0.01, now(), now()),
  (gen_random_uuid()::text, 'Continente',              'Curve',      'cashback', '2026-01-09',  0.64, now(), now()),
  (gen_random_uuid()::text, 'WhatYouExpect',           'Vale',       'survey',   '2026-01-09',  5.00, now(), now()),
  (gen_random_uuid()::text, 'WhatYouExpect',           'Vale',       'survey',   '2026-01-09',  5.00, now(), now()),
  (gen_random_uuid()::text, 'Unibanco',                'Unibanco',   'cashback', '2026-01-08',  5.00, now(), now()),
  (gen_random_uuid()::text, 'Bybit',                   'ByBit',      'cashback', '2026-01-07', 25.00, now(), now()),
  (gen_random_uuid()::text, 'Bybit',                   'ByBit',      'cashback', '2026-01-07', 25.00, now(), now()),
  (gen_random_uuid()::text, 'Amazon',                  'LetyShops',  'cashback', '2026-01-07',  0.63, now(), now()),
  (gen_random_uuid()::text, 'Amazon',                  'LetyShops',  'cashback', '2026-01-07',  2.24, now(), now()),
  (gen_random_uuid()::text, 'Mercadona',               'Curve',      'cashback', '2026-01-04',  0.27, now(), now()),
  (gen_random_uuid()::text, 'beRuby',                  'PayPal',     'survey',   '2026-01-02', 10.00, now(), now())

on conflict (id) do nothing;
